Create skyrim.yaml
StopModReposts/Illegal-Mod-Sites pull request #353
Opened 2021-01-28 18:46 UTC by yggdrasil75

added 2 sites for skyrim.

2021-01-28 18:47 UTC, yggdrasil75 commented
closes #352

2021-12-30 17:44 UTC, dada513 requested changes

2021-12-30 17:44 UTC, dada513 commented on lists/bethesda.yaml
> +    notes: 'specifically designed for child nudity mods. includes reposts of others works, but with nude children added'
This needs to be reworked a bit to comply with the [new api format](https://github.com/StopModReposts/Illegal-Mod-Sites/wiki/API-access-and-formats). Mainly, remove ratings and replace them with `notes` and `reason`

2022-01-02 20:59 UTC, berrysauce commented
Will be added in #421

2022-01-02 20:59 UTC, closed without merging