add new websites (to comply with the new api)
StopModReposts/Illegal-Mod-Sites pull request #423
Opened 2022-01-03 12:09 UTC by Brandonbr1

2022-01-04 07:50 UTC, dada513 requested changes
Also, list should be sorted alphabetically. Once you're done with my review I can sort it before merge

2022-01-04 07:50 UTC, dada513 commented on lists/minecraft.yaml
> +- domain: shadersmods.com
does not redistribute, links to original

2022-01-04 07:50 UTC, dada513 commented on lists/minecraft.yaml
> +- domain: download.komputerswiat.pl
duplicate

2022-01-04 07:50 UTC, dada513 commented on lists/minecraft.yaml
> +- domain: www.mc-mod.net
duplicate

2022-01-04 07:50 UTC, dada513 commented on lists/minecraft.yaml
> +- domain: www.mtmods.com
does not redistr

2022-01-04 07:50 UTC, dada513 commented on lists/minecraft.yaml
> +- domain: 99minecraft.com
duplicate

2022-01-04 07:50 UTC, dada513 commented on lists/minecraft.yaml
> +- domain: mcpedl.com
im not sure about mcpedl, can you give your feedback on #426?

2022-01-06 19:16 UTC, Brandonbr1 commented
@dada513  did all the changes you asked  me to

2022-01-06 19:19 UTC, dada513 commented
> @dada513 did all the changes you asked me to

waiting for @berrysauce feedback on mcpdl

2022-01-06 19:42 UTC, berrysauce requested changes
Remove mcpedl.com for now. We need more time to review/discuss it.

2022-01-06 20:06 UTC, merged