add a few new website
StopModReposts/Illegal-Mod-Sites pull request #459
Opened 2022-01-16 15:05 UTC by Brandonbr1

2022-01-19 21:00 UTC, dada513 requested changes

2022-01-19 21:00 UTC, dada513 commented on lists/minecraft.yaml
> +  reason: Illegal redistribution
set notes to `Fake Optifine website`

2022-01-19 21:03 UTC, dada513 commented
add this to the PR description to properly link issues:

Closes #446 Closes #458 Closes #445

2022-01-20 17:53 UTC, Brandonbr1 commented
@dada513  did all of the changes😀😊 you asked me too

2022-01-20 19:28 UTC, dada513 commented
Thanks, I'll merge when I'm on my PC

Btw, don't close the issues manually, when linked in the PR they will auto close on merge 🙂

2022-01-20 19:50 UTC, dada513 commented on lists/minecraft.yaml
> +-
remote the `-` at the end

2022-01-20 19:50 UTC, dada513 approved these changes
other than the last tiny review, seems good

2022-01-20 19:54 UTC, Brandonbr1 commented
@dada513 ok fixed everything you asked me in your review

2022-01-20 20:08 UTC, dada513 commented
ok waiting for berrysauce review

2022-01-21 20:06 UTC, berrysauce requested changes
Reason (reason: Illegal redistribution) is missing for minecraft-pocket.com and monster-mcpe.com

2022-01-21 22:17 UTC, Brandonbr1 commented
> Reason (reason: Illegal redistribution) is missing for minecraft-pocket.com and monster-mcpe.com

@berrysauce  changes done!

2022-01-22 17:06 UTC, berrysauce approved these changes
Thanks for making the changes!

2022-01-22 17:07 UTC, merged